version: '3'
services:

  db:
    image: postgres:13.9
    container_name: db-senti
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=senti
    ports:
      - "5454:5432"
    networks:
      - ams-network

  backend:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
       - .:/code
    container_name: backend
    image: backend/ams:latest
    env_file: .env
    ports:
        - "8000:8000"
    depends_on:
      - db

networks:
  ams-network:
    driver: bridge

